apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fh6ze4det-python 
  janus-idp.io/tekton: fh6ze4det-python
  backstage.io/kubernetes-id: fh6ze4det-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fh6ze4det-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  