apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fh6ze4det-python
  janus-idp.io/tekton: fh6ze4det-python
  backstage.io/kubernetes-id: fh6ze4det-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fh6ze4det-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
