apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: fh6ze4det-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fh6ze4det-python 
  name: fh6ze4det-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: fh6ze4det-python
    weight: 100 
